// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCinebook.BookingData;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyCinebook.BookingData.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyCinebook.BookingData.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BookingModel");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingSeatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingShowModelId")
                        .HasColumnType("integer");

                    b.Property<char>("Line")
                        .HasColumnType("character(1)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingShowModelId");

                    b.ToTable("BookingSeatModel");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingShowModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingModelId");

                    b.ToTable("BookingShowModel");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingSeatModel", b =>
                {
                    b.HasOne("MyCinebook.BookingData.BookingShowModel", null)
                        .WithMany("Seats")
                        .HasForeignKey("BookingShowModelId");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingShowModel", b =>
                {
                    b.HasOne("MyCinebook.BookingData.BookingModel", null)
                        .WithMany("Shows")
                        .HasForeignKey("BookingModelId");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingModel", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MyCinebook.BookingData.BookingShowModel", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
