name: CI/CD

on:
  push:
    branches:
        - "main"
  workflow_dispatch:

jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-test.yml

  call-publish-schedule-api:
    uses: ./.github/workflows/publish-ghcr.yml

    with:
      docker-file-path: MyCinebook.ScheduleApiService/Dockerfile
      docker-image-name: my-cinebook-schedule-api

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    needs:
    - call-build-and-test

  call-publish-migration-worker:
    uses: ./.github/workflows/publish-ghcr.yml

    with:
      docker-file-path: MyCinebook.MigrationService/Dockerfile
      docker-image-name: my-cinebook-migration-worker

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    needs:
    - call-build-and-test

  call-publish-booking-api:
    uses: ./.github/workflows/publish-ghcr.yml

    with:
      docker-file-path: MyCinebook.BookingApiService/Dockerfile
      docker-image-name: my-cinebook-booking-api

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    needs:
    - call-build-and-test
