name: .NET publish container

on:
  push:
    branches:
        - "main"
  workflow_dispatch:

jobs:
  call-build-and-test:
    uses: ./.github/workflows/dotnet-build-test.yml

  publish:
    name: publish container

    runs-on: ubuntu-latest

    needs:
    - call-build-and-test

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish and push the container image
      run: |
        dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=ghcr.io
