name: Publish

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  publish:
    name: publish

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish and push the container image
      run: |
        cd my-cinebook.ApiService/
        dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=ghcr.io.pubxml
