name: Publish

on:
  workflow_call:
    inputs:
      docker-file-path:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.docker-file-path }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.docker-image-name }}:latest
